---
- name: install java.
  yum:
    name: java
    state: present

- name: create group
  group:
    name: tomcat

- name: create user
  user:
    name: tomcat
    group: tomcat
    home: /home/tomcat

- name: download tomcat7
  get_url:
    url: "{{tomcat_url}}"
    dest: "{{tomcat_dest_path}}"
- name: extract tomcat
  command: /bin/tar -xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/
#    creates: /opt/tomcats/
- name: create directory
  file:
    path: /opt/tomcats/
    state: directory
    owner: tomcat
    group: tomcat    
  
- name: move apache-tomcat in tomcats directory
  command: mv /opt/apache-tomcat-7.0.61 /opt/tomcats/tomcat

- name: create directory
  command: chown -R tomcat. /opt/tomcats/
  
- name: copy start script
  template:
    src: tomcat
    dest: /etc/init.d/tomcat
    mode: 0645

- name: start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
